/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#490013",
        "on-primary-container": "#00176b",
        "error-container": "#a70138",
        "error-dim": "#d73357",
        "surface-container-lowest": "#000000",
        "on-secondary-container": "#eff9ff",
        "surface-bright": "#1f2b49",
        "secondary-dim": "#39bce2",
        "on-primary-fixed-variant": "#001e82",
        "tertiary": "#ff6a9f",
        "tertiary-container": "#ff2d8b",
        "inverse-surface": "#faf8ff",
        "on-tertiary-fixed-variant": "#76003a",
        "on-secondary-fixed": "#003a48",
        "surface-container-high": "#141f38",
        "secondary-container": "#006780",
        "primary": "#99a9ff",
        "on-tertiary-container": "#000000",
        "on-surface": "#dee5ff",
        "background": "#060e20",
        "secondary-fixed": "#82deff",
        "on-error-container": "#ffb2b9",
        "on-tertiary-fixed": "#380018",
        "on-secondary": "#003e4e",
        "tertiary-fixed": "#ff8eb1",
        "secondary-fixed-dim": "#57d2f9",
        "tertiary-fixed-dim": "#ff75a4",
        "surface-dim": "#060e20",
        "surface-container": "#0f1930",
        "surface-variant": "#192540",
        "on-background": "#dee5ff",
        "primary-fixed": "#879aff",
        "tertiary-dim": "#ff6a9f",
        "primary-container": "#879aff",
        "error": "#ff6e84",
        "primary-dim": "#4967f4",
        "primary-fixed-dim": "#748bff",
        "on-tertiary": "#470021",
        "inverse-primary": "#2f4fdd",
        "outline-variant": "#40485d",
        "surface-container-highest": "#192540",
        "on-surface-variant": "#a3aac4",
        "on-secondary-fixed-variant": "#00586e",
        "surface-tint": "#99a9ff",
        "on-primary": "#001f88",
        "outline": "#6d758c",
        "surface-container-low": "#091328",
        "secondary": "#4dc9f1",
        "on-primary-fixed": "#000000",
        "inverse-on-surface": "#4d556b",
        "surface": "#060e20"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
