services:
  - type: web
    name: ing-soft-skills-backend
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
    plan: free
    buildCommand: "pip install -r Backend/requirements.txt"
    startCommand: "uvicorn --app-dir Backend app.main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
